### PR TITLE
Create Angular.html

### PR DESCRIPTION
**Pull request by MelinaMejia95**

### CODE REVIEW

**Comment by danielcb29** [comment]
Hey @MelinaMejia95 great job! 👌 , can you provide us a description of your changes? It could be easier for reviewers to understand what did you do. 

Let me pull that changes and take a look, I don't know what is the purpose of this file , however, If this file will be included in the Angular project, it could be a component. 

Just waiting for your description to do a better review, thanks! 😄

**Comment by alejandronanez** [comment]
👍  on what @danielcb29 said. Can you add a screenshot to this PR? it would be awesome.

Thanks!

Good work BTW. :)

**Comment by MelinaMejia95** [comment]
Oh, I'm sorry, I just did it so quickly last night, the file is the design I made for the newsletter, of course is just like a test design because we still don't have any job offer. Soooo, I made it like if Google was looking for front end developers. 😅 Haha (I'm going to make another one)

I exported the file because it is a bit extensive, so I could not take a photo or a screenshot where the full newsletter was viewed.

**Comment by MelinaMejia95** [comment]
@alejandronanez Yes!!! I didn't know it!! It worked!! 
screencapture-file-c-users-melina-downloads-angular-html-1498155151340

**Comment by alejandronanez** [comment]
I like it!

**Comment by jdjuan** [comment]
I knew I wasn't mistaken when I picked you for the Newsletter design! 😄 

So to answer @danielcb29 's question: We are using MailChimp to register our users, right? MailChimp will automatically send a confirmation email to the user. In MailChimp we have a lot of tools to design the templates. I already gave @MelinaMejia95 the credentiales. She will take at look. This is pretty much how it looks:

screenshot-us16 admin mailchimp com-2017-06-22-13-31-05
screenshot-us16 admin mailchimp com-2017-06-22-13-31-27

**Comment by MelinaMejia95** [comment]
\😄/ I'm glad you liked it! 
Like I said, this is just a test, if you want me to add, remove or modify something, let me know, and I will do it! C: 
I was thinking that it would be great if we create a Facebook page for the community, or maybe an Instagram account, or both! Because in the footer block there's only one "Social follow", Github.

**Comment by jdjuan** [comment]
@MelinaMejia95 that's not a bad idea! I was thinking that we need some sort of Social Media, and you are completely right, maybe Twitter could be a good choice. Do you mind opening an issue **[here]
(https://github.com/angular-medellin/meetup/issues/new)** to see what others may think! 🤙

**Comment by MelinaMejia95** [comment]
@jdjuan Done! 😄

**Comment by jdjuan** [comment]
@MelinaMejia95 and I already made some progress on the MailChimp template, we will close this PR for now! 👍

**Pull request closed without merging**
